### ISSUE TITLE
this pendulum will not reverse thrust swing 

### ISSUE THREAD

**Issue by zdx3578** [biaslab/ReactiveInferencePendulum#1]
thanks your good job !

in https://biaslab.github.io/RxInfer.jl/stable/examples/advanced_examples/Active%20Inference%20Mountain%20car/  
the car will reverse thrust swing , but in this pendulum ,when set big mass, pendulum wont reach the goal ,  and the pendulum not reverse thrust swing ; what the logic or code diff in car and this pendulum ?

thanks very much !

**Comment by albertpod** [comment]
Hello, and thanks for your question!

In the journey of https://biaslab.github.io/RxInfer.jl/stable/examples/advanced_examples/Active%20Inference%20Mountain%20car/, the car does a reverse thrust dance, but in the pendulum's tale, when heavy, it's shy and doesn't reach the goal, no reverse dance. Why so?

It's all in the logic and code. The car's code sings with reverse thrust, making it swing. But in the pendulum's story, with more mass, the code doesn't tell the same tale, so no reaching, no swinging.

Hope this helps to unravel the car and pendulum mystery. More questions? Feel free to ask!

Many thanks!

**Comment by zdx3578** [comment]
is  @model function mountain_car(; T, Fg, Fa, Ff, engine_force_limit) 
the code :

# Inverse engine force, from change in state to corresponding engine force
    h_inv = (delta_s_dot::AbstractVector) -> [atanh(clamp(delta_s_dot[2], -engine_force_limit+1e-3, engine_force_limit-1e-3)/engine_force_limit)] 
    
?

**Comment by albertpod** [comment]
Yes

**Comment by zdx3578** [comment]
and one more: 1.5pi not -0.5pi and not 0.5pi , should use absolute |pi - x|

**Comment by albertpod** [comment]
@zdx3578 I don't understand you.

**Comment by zdx3578** [comment]
Maybe it's irrelevant； when  position in 1.5pi, it will go 1.5pi,not go back 0.5pi
